//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Assets.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AssetsLocation : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AssetsLocation object using the connection string found in the 'AssetsLocation' section of the application configuration file.
        /// </summary>
        public AssetsLocation() : base("name=AssetsLocation", "AssetsLocation")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssetsLocation object.
        /// </summary>
        public AssetsLocation(string connectionString) : base(connectionString, "AssetsLocation")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssetsLocation object.
        /// </summary>
        public AssetsLocation(EntityConnection connection) : base(connection, "AssetsLocation")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Asset_Loc> Asset_Loc
        {
            get
            {
                if ((_Asset_Loc == null))
                {
                    _Asset_Loc = base.CreateObjectSet<Asset_Loc>("Asset_Loc");
                }
                return _Asset_Loc;
            }
        }
        private ObjectSet<Asset_Loc> _Asset_Loc;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Asset_Loc EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAsset_Loc(Asset_Loc asset_Loc)
        {
            base.AddObject("Asset_Loc", asset_Loc);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AssetsLoc", Name="Asset_Loc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Asset_Loc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Asset_Loc object.
        /// </summary>
        /// <param name="ass_Loc_ID">Initial value of the Ass_Loc_ID property.</param>
        /// <param name="ass_Loc">Initial value of the Ass_Loc property.</param>
        public static Asset_Loc CreateAsset_Loc(global::System.Int32 ass_Loc_ID, global::System.String ass_Loc)
        {
            Asset_Loc asset_Loc = new Asset_Loc();
            asset_Loc.Ass_Loc_ID = ass_Loc_ID;
            asset_Loc.Ass_Loc = ass_Loc;
            return asset_Loc;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ass_Loc_ID
        {
            get
            {
                return _Ass_Loc_ID;
            }
            set
            {
                if (_Ass_Loc_ID != value)
                {
                    OnAss_Loc_IDChanging(value);
                    ReportPropertyChanging("Ass_Loc_ID");
                    _Ass_Loc_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ass_Loc_ID");
                    OnAss_Loc_IDChanged();
                }
            }
        }
        private global::System.Int32 _Ass_Loc_ID;
        partial void OnAss_Loc_IDChanging(global::System.Int32 value);
        partial void OnAss_Loc_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ass_Loc
        {
            get
            {
                return _Ass_Loc;
            }
            set
            {
                OnAss_LocChanging(value);
                ReportPropertyChanging("Ass_Loc");
                _Ass_Loc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ass_Loc");
                OnAss_LocChanged();
            }
        }
        private global::System.String _Ass_Loc;
        partial void OnAss_LocChanging(global::System.String value);
        partial void OnAss_LocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ass_Loc_Map_Link
        {
            get
            {
                return _Ass_Loc_Map_Link;
            }
            set
            {
                OnAss_Loc_Map_LinkChanging(value);
                ReportPropertyChanging("Ass_Loc_Map_Link");
                _Ass_Loc_Map_Link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ass_Loc_Map_Link");
                OnAss_Loc_Map_LinkChanged();
            }
        }
        private global::System.String _Ass_Loc_Map_Link;
        partial void OnAss_Loc_Map_LinkChanging(global::System.String value);
        partial void OnAss_Loc_Map_LinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ass_Loc_Lat
        {
            get
            {
                return _Ass_Loc_Lat;
            }
            set
            {
                OnAss_Loc_LatChanging(value);
                ReportPropertyChanging("Ass_Loc_Lat");
                _Ass_Loc_Lat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ass_Loc_Lat");
                OnAss_Loc_LatChanged();
            }
        }
        private global::System.String _Ass_Loc_Lat;
        partial void OnAss_Loc_LatChanging(global::System.String value);
        partial void OnAss_Loc_LatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ass_Loc_Long
        {
            get
            {
                return _Ass_Loc_Long;
            }
            set
            {
                OnAss_Loc_LongChanging(value);
                ReportPropertyChanging("Ass_Loc_Long");
                _Ass_Loc_Long = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ass_Loc_Long");
                OnAss_Loc_LongChanged();
            }
        }
        private global::System.String _Ass_Loc_Long;
        partial void OnAss_Loc_LongChanging(global::System.String value);
        partial void OnAss_Loc_LongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Ass_Loc_Des
        {
            get
            {
                return _Ass_Loc_Des;
            }
            set
            {
                OnAss_Loc_DesChanging(value);
                ReportPropertyChanging("Ass_Loc_Des");
                _Ass_Loc_Des = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Ass_Loc_Des");
                OnAss_Loc_DesChanged();
            }
        }
        private global::System.String _Ass_Loc_Des;
        partial void OnAss_Loc_DesChanging(global::System.String value);
        partial void OnAss_Loc_DesChanged();

        #endregion
    
    }

    #endregion
    
}
