//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Assets.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AssetsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AssetsEntities object using the connection string found in the 'AssetsEntities' section of the application configuration file.
        /// </summary>
        public AssetsEntities() : base("name=AssetsEntities", "AssetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssetsEntities object.
        /// </summary>
        public AssetsEntities(string connectionString) : base(connectionString, "AssetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssetsEntities object.
        /// </summary>
        public AssetsEntities(EntityConnection connection) : base(connection, "AssetsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Asset_History> Asset_History
        {
            get
            {
                if ((_Asset_History == null))
                {
                    _Asset_History = base.CreateObjectSet<Asset_History>("Asset_History");
                }
                return _Asset_History;
            }
        }
        private ObjectSet<Asset_History> _Asset_History;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Asset_History EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAsset_History(Asset_History asset_History)
        {
            base.AddObject("Asset_History", asset_History);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AssetsHistory", Name="Asset_History")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Asset_History : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Asset_History object.
        /// </summary>
        /// <param name="ass_His_ID">Initial value of the Ass_His_ID property.</param>
        /// <param name="ass_ID">Initial value of the Ass_ID property.</param>
        /// <param name="iTRID">Initial value of the ITRID property.</param>
        /// <param name="iTR_Eff_Date">Initial value of the ITR_Eff_Date property.</param>
        public static Asset_History CreateAsset_History(global::System.Int32 ass_His_ID, global::System.Int32 ass_ID, global::System.String iTRID, global::System.DateTime iTR_Eff_Date)
        {
            Asset_History asset_History = new Asset_History();
            asset_History.Ass_His_ID = ass_His_ID;
            asset_History.Ass_ID = ass_ID;
            asset_History.ITRID = iTRID;
            asset_History.ITR_Eff_Date = iTR_Eff_Date;
            return asset_History;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ass_His_ID
        {
            get
            {
                return _Ass_His_ID;
            }
            set
            {
                if (_Ass_His_ID != value)
                {
                    OnAss_His_IDChanging(value);
                    ReportPropertyChanging("Ass_His_ID");
                    _Ass_His_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Ass_His_ID");
                    OnAss_His_IDChanged();
                }
            }
        }
        private global::System.Int32 _Ass_His_ID;
        partial void OnAss_His_IDChanging(global::System.Int32 value);
        partial void OnAss_His_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Ass_ID
        {
            get
            {
                return _Ass_ID;
            }
            set
            {
                OnAss_IDChanging(value);
                ReportPropertyChanging("Ass_ID");
                _Ass_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ass_ID");
                OnAss_IDChanged();
            }
        }
        private global::System.Int32 _Ass_ID;
        partial void OnAss_IDChanging(global::System.Int32 value);
        partial void OnAss_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ITRID
        {
            get
            {
                return _ITRID;
            }
            set
            {
                OnITRIDChanging(value);
                ReportPropertyChanging("ITRID");
                _ITRID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ITRID");
                OnITRIDChanged();
            }
        }
        private global::System.String _ITRID;
        partial void OnITRIDChanging(global::System.String value);
        partial void OnITRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ITR_Eff_Date
        {
            get
            {
                return _ITR_Eff_Date;
            }
            set
            {
                OnITR_Eff_DateChanging(value);
                ReportPropertyChanging("ITR_Eff_Date");
                _ITR_Eff_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ITR_Eff_Date");
                OnITR_Eff_DateChanged();
            }
        }
        private global::System.DateTime _ITR_Eff_Date;
        partial void OnITR_Eff_DateChanging(global::System.DateTime value);
        partial void OnITR_Eff_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Return_Date
        {
            get
            {
                return _Return_Date;
            }
            set
            {
                OnReturn_DateChanging(value);
                ReportPropertyChanging("Return_Date");
                _Return_Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Return_Date");
                OnReturn_DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Return_Date;
        partial void OnReturn_DateChanging(Nullable<global::System.DateTime> value);
        partial void OnReturn_DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Des
        {
            get
            {
                return _Des;
            }
            set
            {
                OnDesChanging(value);
                ReportPropertyChanging("Des");
                _Des = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Des");
                OnDesChanged();
            }
        }
        private global::System.String _Des;
        partial void OnDesChanging(global::System.String value);
        partial void OnDesChanged();

        #endregion
    
    }

    #endregion
    
}
