//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Assets.Models
{

    public class Assets
    {
/*        public int LabelID { get; set; }
        public int AssetTypeID { get; set; }
        public int LocationID { get; set; }
        public int EmployeeID { get; set; }
        public int ITRID { get; set; }
        public string Replacement { get; set; }
        public string SerialNo { get; set; }
        public string OS { get; set; }
        public string [Windows Key] { get; set; }
        public int ProductNo { get; set; }
        public string Model { get; set; }
        public int TimeStamp  { get; set; } //type 
        public
*/
    }
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AssetManagementNewEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AssetManagementNewEntities object using the connection string found in the 'AssetManagementNewEntities' section of the application configuration file.
        /// </summary>
        public AssetManagementNewEntities() : base("name=AssetManagementNewEntities", "AssetManagementNewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssetManagementNewEntities object.
        /// </summary>
        public AssetManagementNewEntities(string connectionString) : base(connectionString, "AssetManagementNewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssetManagementNewEntities object.
        /// </summary>
        public AssetManagementNewEntities(EntityConnection connection) : base(connection, "AssetManagementNewEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Asset> Assets
        {
            get
            {
                if ((_Assets == null))
                {
                    _Assets = base.CreateObjectSet<Asset>("Assets");
                }
                return _Assets;
            }
        }
        private ObjectSet<Asset> _Assets;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Assets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAssets(Asset asset)
        {
            base.AddObject("Assets", asset);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AssetManagementNewModel", Name="Asset")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Asset : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Asset object.
        /// </summary>
        /// <param name="labelID">Initial value of the LabelID property.</param>
        /// <param name="assetTypeID">Initial value of the AssetTypeID property.</param>
        /// <param name="locationID">Initial value of the LocationID property.</param>
        /// <param name="replacement">Initial value of the Replacement property.</param>
        /// <param name="serialNo">Initial value of the SerialNo property.</param>
        /// <param name="timeStamp">Initial value of the TimeStamp property.</param>
        public static Asset CreateAsset(global::System.String labelID, global::System.String assetTypeID, global::System.String locationID, global::System.Boolean replacement, global::System.String serialNo, global::System.DateTime timeStamp)
        {
            Asset asset = new Asset();
            asset.LabelID = labelID;
            asset.AssetTypeID = assetTypeID;
            asset.LocationID = locationID;
            asset.Replacement = replacement;
            asset.SerialNo = serialNo;
            asset.TimeStamp = timeStamp;
            return asset;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LabelID
        {
            get
            {
                return _LabelID;
            }
            set
            {
                if (_LabelID != value)
                {
                    OnLabelIDChanging(value);
                    ReportPropertyChanging("LabelID");
                    _LabelID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("LabelID");
                    OnLabelIDChanged();
                }
            }
        }
        private global::System.String _LabelID;
        partial void OnLabelIDChanging(global::System.String value);
        partial void OnLabelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssetTypeID
        {
            get
            {
                return _AssetTypeID;
            }
            set
            {
                OnAssetTypeIDChanging(value);
                ReportPropertyChanging("AssetTypeID");
                _AssetTypeID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssetTypeID");
                OnAssetTypeIDChanged();
            }
        }
        private global::System.String _AssetTypeID;
        partial void OnAssetTypeIDChanging(global::System.String value);
        partial void OnAssetTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private global::System.String _LocationID;
        partial void OnLocationIDChanging(global::System.String value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private global::System.String _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.String value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ITRID
        {
            get
            {
                return _ITRID;
            }
            set
            {
                OnITRIDChanging(value);
                ReportPropertyChanging("ITRID");
                _ITRID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ITRID");
                OnITRIDChanged();
            }
        }
        private global::System.String _ITRID;
        partial void OnITRIDChanging(global::System.String value);
        partial void OnITRIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Replacement
        {
            get
            {
                return _Replacement;
            }
            set
            {
                OnReplacementChanging(value);
                ReportPropertyChanging("Replacement");
                _Replacement = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Replacement");
                OnReplacementChanged();
            }
        }
        private global::System.Boolean _Replacement;
        partial void OnReplacementChanging(global::System.Boolean value);
        partial void OnReplacementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SerialNo
        {
            get
            {
                return _SerialNo;
            }
            set
            {
                OnSerialNoChanging(value);
                ReportPropertyChanging("SerialNo");
                _SerialNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SerialNo");
                OnSerialNoChanged();
            }
        }
        private global::System.String _SerialNo;
        partial void OnSerialNoChanging(global::System.String value);
        partial void OnSerialNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OS
        {
            get
            {
                return _OS;
            }
            set
            {
                OnOSChanging(value);
                ReportPropertyChanging("OS");
                _OS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OS");
                OnOSChanged();
            }
        }
        private global::System.String _OS;
        partial void OnOSChanging(global::System.String value);
        partial void OnOSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Windows_Key
        {
            get
            {
                return _Windows_Key;
            }
            set
            {
                OnWindows_KeyChanging(value);
                ReportPropertyChanging("Windows_Key");
                _Windows_Key = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Windows_Key");
                OnWindows_KeyChanged();
            }
        }
        private global::System.String _Windows_Key;
        partial void OnWindows_KeyChanging(global::System.String value);
        partial void OnWindows_KeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductNo
        {
            get
            {
                return _ProductNo;
            }
            set
            {
                OnProductNoChanging(value);
                ReportPropertyChanging("ProductNo");
                _ProductNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProductNo");
                OnProductNoChanged();
            }
        }
        private global::System.String _ProductNo;
        partial void OnProductNoChanging(global::System.String value);
        partial void OnProductNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private global::System.DateTime _TimeStamp;
        partial void OnTimeStampChanging(global::System.DateTime value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String History
        {
            get
            {
                return _History;
            }
            set
            {
                OnHistoryChanging(value);
                ReportPropertyChanging("History");
                _History = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("History");
                OnHistoryChanged();
            }
        }
        private global::System.String _History;
        partial void OnHistoryChanging(global::System.String value);
        partial void OnHistoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }

    #endregion

    
}
