//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Assets.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AssetManagementNewEntities6 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AssetManagementNewEntities6 object using the connection string found in the 'AssetManagementNewEntities6' section of the application configuration file.
        /// </summary>
        public AssetManagementNewEntities6() : base("name=AssetManagementNewEntities6", "AssetManagementNewEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssetManagementNewEntities6 object.
        /// </summary>
        public AssetManagementNewEntities6(string connectionString) : base(connectionString, "AssetManagementNewEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AssetManagementNewEntities6 object.
        /// </summary>
        public AssetManagementNewEntities6(EntityConnection connection) : base(connection, "AssetManagementNewEntities6")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Warranty> Warranties
        {
            get
            {
                if ((_Warranties == null))
                {
                    _Warranties = base.CreateObjectSet<Warranty>("Warranties");
                }
                return _Warranties;
            }
        }
        private ObjectSet<Warranty> _Warranties;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Warranties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWarranties(Warranty warranty)
        {
            base.AddObject("Warranties", warranty);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AssetManagementNewModel4", Name="Warranty")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Warranty : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Warranty object.
        /// </summary>
        /// <param name="vendorName">Initial value of the VendorName property.</param>
        /// <param name="priority">Initial value of the Priority property.</param>
        /// <param name="warrantyNumber">Initial value of the WarrantyNumber property.</param>
        /// <param name="assetTypeID">Initial value of the AssetTypeID property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        public static Warranty CreateWarranty(global::System.String vendorName, global::System.Int32 priority, global::System.Int32 warrantyNumber, global::System.String assetTypeID, global::System.String model, global::System.Int32 startDate, global::System.Int32 endDate)
        {
            Warranty warranty = new Warranty();
            warranty.VendorName = vendorName;
            warranty.Priority = priority;
            warranty.WarrantyNumber = warrantyNumber;
            warranty.AssetTypeID = assetTypeID;
            warranty.Model = model;
            warranty.StartDate = startDate;
            warranty.EndDate = endDate;
            return warranty;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VendorName
        {
            get
            {
                return _VendorName;
            }
            set
            {
                OnVendorNameChanging(value);
                ReportPropertyChanging("VendorName");
                _VendorName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VendorName");
                OnVendorNameChanged();
            }
        }
        private global::System.String _VendorName;
        partial void OnVendorNameChanging(global::System.String value);
        partial void OnVendorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.Int32 _Priority;
        partial void OnPriorityChanging(global::System.Int32 value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WarrantyNumber
        {
            get
            {
                return _WarrantyNumber;
            }
            set
            {
                if (_WarrantyNumber != value)
                {
                    OnWarrantyNumberChanging(value);
                    ReportPropertyChanging("WarrantyNumber");
                    _WarrantyNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WarrantyNumber");
                    OnWarrantyNumberChanged();
                }
            }
        }
        private global::System.Int32 _WarrantyNumber;
        partial void OnWarrantyNumberChanging(global::System.Int32 value);
        partial void OnWarrantyNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AssetTypeID
        {
            get
            {
                return _AssetTypeID;
            }
            set
            {
                OnAssetTypeIDChanging(value);
                ReportPropertyChanging("AssetTypeID");
                _AssetTypeID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AssetTypeID");
                OnAssetTypeIDChanged();
            }
        }
        private global::System.String _AssetTypeID;
        partial void OnAssetTypeIDChanging(global::System.String value);
        partial void OnAssetTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.Int32 _StartDate;
        partial void OnStartDateChanging(global::System.Int32 value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.Int32 _EndDate;
        partial void OnEndDateChanging(global::System.Int32 value);
        partial void OnEndDateChanged();

        #endregion

    
    }

    #endregion

    
}
