//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ISE_TEST_V1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AnswersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AnswersEntities object using the connection string found in the 'AnswersEntities' section of the application configuration file.
        /// </summary>
        public AnswersEntities() : base("name=AnswersEntities", "AnswersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AnswersEntities object.
        /// </summary>
        public AnswersEntities(string connectionString) : base(connectionString, "AnswersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AnswersEntities object.
        /// </summary>
        public AnswersEntities(EntityConnection connection) : base(connection, "AnswersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Answer> Answers
        {
            get
            {
                if ((_Answers == null))
                {
                    _Answers = base.CreateObjectSet<Answer>("Answers");
                }
                return _Answers;
            }
        }
        private ObjectSet<Answer> _Answers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Answers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnswers(Answer answer)
        {
            base.AddObject("Answers", answer);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ISE_TEST_1Model6", Name="Answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Answer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Answer object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="q_ID">Initial value of the Q_ID property.</param>
        public static Answer CreateAnswer(global::System.Int32 id, global::System.Int32 q_ID)
        {
            Answer answer = new Answer();
            answer.ID = id;
            answer.Q_ID = q_ID;
            return answer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PID
        {
            get
            {
                return _PID;
            }
            set
            {
                OnPIDChanging(value);
                ReportPropertyChanging("PID");
                _PID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PID");
                OnPIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PID;
        partial void OnPIDChanging(Nullable<global::System.Int32> value);
        partial void OnPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Q_ID
        {
            get
            {
                return _Q_ID;
            }
            set
            {
                OnQ_IDChanging(value);
                ReportPropertyChanging("Q_ID");
                _Q_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Q_ID");
                OnQ_IDChanged();
            }
        }
        private global::System.Int32 _Q_ID;
        partial void OnQ_IDChanging(global::System.Int32 value);
        partial void OnQ_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_Right
        {
            get
            {
                return _is_Right;
            }
            set
            {
                Onis_RightChanging(value);
                ReportPropertyChanging("is_Right");
                _is_Right = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_Right");
                Onis_RightChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_Right;
        partial void Onis_RightChanging(Nullable<global::System.Boolean> value);
        partial void Onis_RightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> A_Order
        {
            get
            {
                return _A_Order;
            }
            set
            {
                OnA_OrderChanging(value);
                ReportPropertyChanging("A_Order");
                _A_Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("A_Order");
                OnA_OrderChanged();
            }
        }
        private Nullable<global::System.Int16> _A_Order;
        partial void OnA_OrderChanging(Nullable<global::System.Int16> value);
        partial void OnA_OrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private Nullable<global::System.Int32> _value;
        partial void OnvalueChanging(Nullable<global::System.Int32> value);
        partial void OnvalueChanged();

        #endregion
    
    }

    #endregion
    
}
