//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ISE_TEST_V1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Can_TestsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Can_TestsEntities object using the connection string found in the 'Can_TestsEntities' section of the application configuration file.
        /// </summary>
        public Can_TestsEntities() : base("name=Can_TestsEntities", "Can_TestsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Can_TestsEntities object.
        /// </summary>
        public Can_TestsEntities(string connectionString) : base(connectionString, "Can_TestsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Can_TestsEntities object.
        /// </summary>
        public Can_TestsEntities(EntityConnection connection) : base(connection, "Can_TestsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<C_T_R> C_T_R
        {
            get
            {
                if ((_C_T_R == null))
                {
                    _C_T_R = base.CreateObjectSet<C_T_R>("C_T_R");
                }
                return _C_T_R;
            }
        }
        private ObjectSet<C_T_R> _C_T_R;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the C_T_R EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToC_T_R(C_T_R c_T_R)
        {
            base.AddObject("C_T_R", c_T_R);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ISE_TEST_1Model2", Name="C_T_R")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class C_T_R : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new C_T_R object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="t_ID">Initial value of the T_ID property.</param>
        /// <param name="c_ID">Initial value of the C_ID property.</param>
        /// <param name="is_submitted">Initial value of the is_submitted property.</param>
        public static C_T_R CreateC_T_R(global::System.Int32 id, global::System.Int32 t_ID, global::System.Int32 c_ID, global::System.Boolean is_submitted)
        {
            C_T_R c_T_R = new C_T_R();
            c_T_R.ID = id;
            c_T_R.T_ID = t_ID;
            c_T_R.C_ID = c_ID;
            c_T_R.is_submitted = is_submitted;
            return c_T_R;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 T_ID
        {
            get
            {
                return _T_ID;
            }
            set
            {
                OnT_IDChanging(value);
                ReportPropertyChanging("T_ID");
                _T_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("T_ID");
                OnT_IDChanged();
            }
        }
        private global::System.Int32 _T_ID;
        partial void OnT_IDChanging(global::System.Int32 value);
        partial void OnT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_ID
        {
            get
            {
                return _C_ID;
            }
            set
            {
                OnC_IDChanging(value);
                ReportPropertyChanging("C_ID");
                _C_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_ID");
                OnC_IDChanged();
            }
        }
        private global::System.Int32 _C_ID;
        partial void OnC_IDChanging(global::System.Int32 value);
        partial void OnC_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean is_submitted
        {
            get
            {
                return _is_submitted;
            }
            set
            {
                Onis_submittedChanging(value);
                ReportPropertyChanging("is_submitted");
                _is_submitted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_submitted");
                Onis_submittedChanged();
            }
        }
        private global::System.Boolean _is_submitted;
        partial void Onis_submittedChanging(global::System.Boolean value);
        partial void Onis_submittedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Isu
        {
            get
            {
                return _Date_Isu;
            }
            set
            {
                OnDate_IsuChanging(value);
                ReportPropertyChanging("Date_Isu");
                _Date_Isu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Isu");
                OnDate_IsuChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Isu;
        partial void OnDate_IsuChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_IsuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_to_Set
        {
            get
            {
                return _Date_to_Set;
            }
            set
            {
                OnDate_to_SetChanging(value);
                ReportPropertyChanging("Date_to_Set");
                _Date_to_Set = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_to_Set");
                OnDate_to_SetChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_to_Set;
        partial void OnDate_to_SetChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_to_SetChanged();

        #endregion
    
    }

    #endregion
    
}
