//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ISE_TEST_V1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QTEntities12 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QTEntities12 object using the connection string found in the 'QTEntities12' section of the application configuration file.
        /// </summary>
        public QTEntities12() : base("name=QTEntities12", "QTEntities12")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QTEntities12 object.
        /// </summary>
        public QTEntities12(string connectionString) : base(connectionString, "QTEntities12")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QTEntities12 object.
        /// </summary>
        public QTEntities12(EntityConnection connection) : base(connection, "QTEntities12")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Q_T_R> Q_T_R
        {
            get
            {
                if ((_Q_T_R == null))
                {
                    _Q_T_R = base.CreateObjectSet<Q_T_R>("Q_T_R");
                }
                return _Q_T_R;
            }
        }
        private ObjectSet<Q_T_R> _Q_T_R;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Q_T_R EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQ_T_R(Q_T_R q_T_R)
        {
            base.AddObject("Q_T_R", q_T_R);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ISE_TEST_1Model5", Name="Q_T_R")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Q_T_R : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Q_T_R object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="q_ID">Initial value of the Q_ID property.</param>
        /// <param name="t_ID">Initial value of the T_ID property.</param>
        /// <param name="q_Type">Initial value of the Q_Type property.</param>
        public static Q_T_R CreateQ_T_R(global::System.Int32 id, global::System.Int32 q_ID, global::System.Int32 t_ID, global::System.Int16 q_Type)
        {
            Q_T_R q_T_R = new Q_T_R();
            q_T_R.ID = id;
            q_T_R.Q_ID = q_ID;
            q_T_R.T_ID = t_ID;
            q_T_R.Q_Type = q_Type;
            return q_T_R;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Q_ID
        {
            get
            {
                return _Q_ID;
            }
            set
            {
                OnQ_IDChanging(value);
                ReportPropertyChanging("Q_ID");
                _Q_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Q_ID");
                OnQ_IDChanged();
            }
        }
        private global::System.Int32 _Q_ID;
        partial void OnQ_IDChanging(global::System.Int32 value);
        partial void OnQ_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 T_ID
        {
            get
            {
                return _T_ID;
            }
            set
            {
                OnT_IDChanging(value);
                ReportPropertyChanging("T_ID");
                _T_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("T_ID");
                OnT_IDChanged();
            }
        }
        private global::System.Int32 _T_ID;
        partial void OnT_IDChanging(global::System.Int32 value);
        partial void OnT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Q_Type
        {
            get
            {
                return _Q_Type;
            }
            set
            {
                OnQ_TypeChanging(value);
                ReportPropertyChanging("Q_Type");
                _Q_Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Q_Type");
                OnQ_TypeChanged();
            }
        }
        private global::System.Int16 _Q_Type;
        partial void OnQ_TypeChanging(global::System.Int16 value);
        partial void OnQ_TypeChanged();

        #endregion
    
    }

    #endregion
    
}
