//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ISE_TEST_V1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Roles_Manager_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Roles_Manager_Entities object using the connection string found in the 'Roles_Manager_Entities' section of the application configuration file.
        /// </summary>
        public Roles_Manager_Entities() : base("name=Roles_Manager_Entities", "Roles_Manager_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Roles_Manager_Entities object.
        /// </summary>
        public Roles_Manager_Entities(string connectionString) : base(connectionString, "Roles_Manager_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Roles_Manager_Entities object.
        /// </summary>
        public Roles_Manager_Entities(EntityConnection connection) : base(connection, "Roles_Manager_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Roles_Manager> Roles_Manager
        {
            get
            {
                if ((_Roles_Manager == null))
                {
                    _Roles_Manager = base.CreateObjectSet<Roles_Manager>("Roles_Manager");
                }
                return _Roles_Manager;
            }
        }
        private ObjectSet<Roles_Manager> _Roles_Manager;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles_Manager EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles_Manager(Roles_Manager roles_Manager)
        {
            base.AddObject("Roles_Manager", roles_Manager);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ISE_TEST_1Model10", Name="Roles_Manager")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Roles_Manager : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Roles_Manager object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="roleName">Initial value of the RoleName property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        public static Roles_Manager CreateRoles_Manager(global::System.Int32 id, global::System.String roleName, global::System.String userName)
        {
            Roles_Manager roles_Manager = new Roles_Manager();
            roles_Manager.ID = id;
            roles_Manager.RoleName = roleName;
            roles_Manager.UserName = userName;
            return roles_Manager;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoleName
        {
            get
            {
                return _RoleName;
            }
            set
            {
                OnRoleNameChanging(value);
                ReportPropertyChanging("RoleName");
                _RoleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RoleName");
                OnRoleNameChanged();
            }
        }
        private global::System.String _RoleName;
        partial void OnRoleNameChanging(global::System.String value);
        partial void OnRoleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion
    
    }

    #endregion
    
}
