//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ISE_TEST_V1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Answer_Log : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Answer_Log object using the connection string found in the 'Answer_Log' section of the application configuration file.
        /// </summary>
        public Answer_Log() : base("name=Answer_Log", "Answer_Log")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Answer_Log object.
        /// </summary>
        public Answer_Log(string connectionString) : base(connectionString, "Answer_Log")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Answer_Log object.
        /// </summary>
        public Answer_Log(EntityConnection connection) : base(connection, "Answer_Log")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Answers_Log> Answers_Log
        {
            get
            {
                if ((_Answers_Log == null))
                {
                    _Answers_Log = base.CreateObjectSet<Answers_Log>("Answers_Log");
                }
                return _Answers_Log;
            }
        }
        private ObjectSet<Answers_Log> _Answers_Log;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Answers_Log EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAnswers_Log(Answers_Log answers_Log)
        {
            base.AddObject("Answers_Log", answers_Log);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ISE_TEST_1Model8", Name="Answers_Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Answers_Log : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Answers_Log object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="c_T_R_ID">Initial value of the C_T_R_ID property.</param>
        /// <param name="q_ID">Initial value of the Q_ID property.</param>
        /// <param name="a_ID">Initial value of the A_ID property.</param>
        public static Answers_Log CreateAnswers_Log(global::System.Int32 id, global::System.Int32 c_T_R_ID, global::System.Int32 q_ID, global::System.Int32 a_ID)
        {
            Answers_Log answers_Log = new Answers_Log();
            answers_Log.ID = id;
            answers_Log.C_T_R_ID = c_T_R_ID;
            answers_Log.Q_ID = q_ID;
            answers_Log.A_ID = a_ID;
            return answers_Log;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_T_R_ID
        {
            get
            {
                return _C_T_R_ID;
            }
            set
            {
                OnC_T_R_IDChanging(value);
                ReportPropertyChanging("C_T_R_ID");
                _C_T_R_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_T_R_ID");
                OnC_T_R_IDChanged();
            }
        }
        private global::System.Int32 _C_T_R_ID;
        partial void OnC_T_R_IDChanging(global::System.Int32 value);
        partial void OnC_T_R_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Q_ID
        {
            get
            {
                return _Q_ID;
            }
            set
            {
                OnQ_IDChanging(value);
                ReportPropertyChanging("Q_ID");
                _Q_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Q_ID");
                OnQ_IDChanged();
            }
        }
        private global::System.Int32 _Q_ID;
        partial void OnQ_IDChanging(global::System.Int32 value);
        partial void OnQ_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 A_ID
        {
            get
            {
                return _A_ID;
            }
            set
            {
                OnA_IDChanging(value);
                ReportPropertyChanging("A_ID");
                _A_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("A_ID");
                OnA_IDChanged();
            }
        }
        private global::System.Int32 _A_ID;
        partial void OnA_IDChanging(global::System.Int32 value);
        partial void OnA_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_marked
        {
            get
            {
                return _is_marked;
            }
            set
            {
                Onis_markedChanging(value);
                ReportPropertyChanging("is_marked");
                _is_marked = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_marked");
                Onis_markedChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_marked;
        partial void Onis_markedChanging(Nullable<global::System.Boolean> value);
        partial void Onis_markedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> need_rev
        {
            get
            {
                return _need_rev;
            }
            set
            {
                Onneed_revChanging(value);
                ReportPropertyChanging("need_rev");
                _need_rev = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("need_rev");
                Onneed_revChanged();
            }
        }
        private Nullable<global::System.Boolean> _need_rev;
        partial void Onneed_revChanging(Nullable<global::System.Boolean> value);
        partial void Onneed_revChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PID
        {
            get
            {
                return _PID;
            }
            set
            {
                OnPIDChanging(value);
                ReportPropertyChanging("PID");
                _PID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PID");
                OnPIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PID;
        partial void OnPIDChanging(Nullable<global::System.Int32> value);
        partial void OnPIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date_Submitted
        {
            get
            {
                return _Date_Submitted;
            }
            set
            {
                OnDate_SubmittedChanging(value);
                ReportPropertyChanging("Date_Submitted");
                _Date_Submitted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date_Submitted");
                OnDate_SubmittedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date_Submitted;
        partial void OnDate_SubmittedChanging(Nullable<global::System.DateTime> value);
        partial void OnDate_SubmittedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private Nullable<global::System.Int32> _value;
        partial void OnvalueChanging(Nullable<global::System.Int32> value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_right
        {
            get
            {
                return _is_right;
            }
            set
            {
                Onis_rightChanging(value);
                ReportPropertyChanging("is_right");
                _is_right = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_right");
                Onis_rightChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_right;
        partial void Onis_rightChanging(Nullable<global::System.Boolean> value);
        partial void Onis_rightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_wrong
        {
            get
            {
                return _is_wrong;
            }
            set
            {
                Onis_wrongChanging(value);
                ReportPropertyChanging("is_wrong");
                _is_wrong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_wrong");
                Onis_wrongChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_wrong;
        partial void Onis_wrongChanging(Nullable<global::System.Boolean> value);
        partial void Onis_wrongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_answered
        {
            get
            {
                return _is_answered;
            }
            set
            {
                Onis_answeredChanging(value);
                ReportPropertyChanging("is_answered");
                _is_answered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_answered");
                Onis_answeredChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_answered;
        partial void Onis_answeredChanging(Nullable<global::System.Boolean> value);
        partial void Onis_answeredChanged();

        #endregion
    
    }

    #endregion
    
}
