//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ISE_TEST_V1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TempResultEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TempResultEntities object using the connection string found in the 'TempResultEntities' section of the application configuration file.
        /// </summary>
        public TempResultEntities() : base("name=TempResultEntities", "TempResultEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TempResultEntities object.
        /// </summary>
        public TempResultEntities(string connectionString) : base(connectionString, "TempResultEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TempResultEntities object.
        /// </summary>
        public TempResultEntities(EntityConnection connection) : base(connection, "TempResultEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Temp_Result> Temp_Result
        {
            get
            {
                if ((_Temp_Result == null))
                {
                    _Temp_Result = base.CreateObjectSet<Temp_Result>("Temp_Result");
                }
                return _Temp_Result;
            }
        }
        private ObjectSet<Temp_Result> _Temp_Result;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Temp_Result EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemp_Result(Temp_Result temp_Result)
        {
            base.AddObject("Temp_Result", temp_Result);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ISE_TEST_1Model3", Name="Temp_Result")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Temp_Result : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Temp_Result object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="c_T_R_ID">Initial value of the C_T_R_ID property.</param>
        /// <param name="total_Marks">Initial value of the Total_Marks property.</param>
        /// <param name="user_Marks">Initial value of the User_Marks property.</param>
        /// <param name="n_Q_M">Initial value of the N_Q_M property.</param>
        /// <param name="result">Initial value of the Result property.</param>
        public static Temp_Result CreateTemp_Result(global::System.Int32 id, global::System.Int32 c_T_R_ID, global::System.Double total_Marks, global::System.Double user_Marks, global::System.Int32 n_Q_M, global::System.Double result)
        {
            Temp_Result temp_Result = new Temp_Result();
            temp_Result.ID = id;
            temp_Result.C_T_R_ID = c_T_R_ID;
            temp_Result.Total_Marks = total_Marks;
            temp_Result.User_Marks = user_Marks;
            temp_Result.N_Q_M = n_Q_M;
            temp_Result.Result = result;
            return temp_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 C_T_R_ID
        {
            get
            {
                return _C_T_R_ID;
            }
            set
            {
                OnC_T_R_IDChanging(value);
                ReportPropertyChanging("C_T_R_ID");
                _C_T_R_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("C_T_R_ID");
                OnC_T_R_IDChanged();
            }
        }
        private global::System.Int32 _C_T_R_ID;
        partial void OnC_T_R_IDChanging(global::System.Int32 value);
        partial void OnC_T_R_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Total_Marks
        {
            get
            {
                return _Total_Marks;
            }
            set
            {
                OnTotal_MarksChanging(value);
                ReportPropertyChanging("Total_Marks");
                _Total_Marks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Total_Marks");
                OnTotal_MarksChanged();
            }
        }
        private global::System.Double _Total_Marks;
        partial void OnTotal_MarksChanging(global::System.Double value);
        partial void OnTotal_MarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double User_Marks
        {
            get
            {
                return _User_Marks;
            }
            set
            {
                OnUser_MarksChanging(value);
                ReportPropertyChanging("User_Marks");
                _User_Marks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("User_Marks");
                OnUser_MarksChanged();
            }
        }
        private global::System.Double _User_Marks;
        partial void OnUser_MarksChanging(global::System.Double value);
        partial void OnUser_MarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> N_Q_N_R
        {
            get
            {
                return _N_Q_N_R;
            }
            set
            {
                OnN_Q_N_RChanging(value);
                ReportPropertyChanging("N_Q_N_R");
                _N_Q_N_R = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N_Q_N_R");
                OnN_Q_N_RChanged();
            }
        }
        private Nullable<global::System.Int32> _N_Q_N_R;
        partial void OnN_Q_N_RChanging(Nullable<global::System.Int32> value);
        partial void OnN_Q_N_RChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> N_Q_N_M
        {
            get
            {
                return _N_Q_N_M;
            }
            set
            {
                OnN_Q_N_MChanging(value);
                ReportPropertyChanging("N_Q_N_M");
                _N_Q_N_M = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N_Q_N_M");
                OnN_Q_N_MChanged();
            }
        }
        private Nullable<global::System.Int32> _N_Q_N_M;
        partial void OnN_Q_N_MChanging(Nullable<global::System.Int32> value);
        partial void OnN_Q_N_MChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 N_Q_M
        {
            get
            {
                return _N_Q_M;
            }
            set
            {
                OnN_Q_MChanging(value);
                ReportPropertyChanging("N_Q_M");
                _N_Q_M = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("N_Q_M");
                OnN_Q_MChanged();
            }
        }
        private global::System.Int32 _N_Q_M;
        partial void OnN_Q_MChanging(global::System.Int32 value);
        partial void OnN_Q_MChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Result
        {
            get
            {
                return _Result;
            }
            set
            {
                OnResultChanging(value);
                ReportPropertyChanging("Result");
                _Result = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Result");
                OnResultChanged();
            }
        }
        private global::System.Double _Result;
        partial void OnResultChanging(global::System.Double value);
        partial void OnResultChanged();

        #endregion
    
    }

    #endregion
    
}
