/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ISE_Test_EnginConfigure.java
 *
 * Created on Jul 30, 2010, 1:28:19 AM
 */

package ise_test_engine;

import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import org.jdesktop.application.Action;

/**
 *
 * @author TOSHIBA
 */

public class ISE_Test_EngineConfigure extends javax.swing.JFrame {

    /** Creates new form ISE_Test_EnginConfigure */
    public ISE_Test_EngineConfigure() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Admin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Server = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Port = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DB_User = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Ins = new javax.swing.JTextField();
        Test = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        DB_Pass = new javax.swing.JPasswordField();
        Pass = new javax.swing.JPasswordField();
        Con = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ise_test_engine.ISE_Test_EngineApp.class).getContext().getResourceMap(ISE_Test_EngineConfigure.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        Admin.setName("Admin"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        Server.setName("Server"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        Port.setName("Port"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        DB.setName("DB"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        DB_User.setText(resourceMap.getString("DB_User.text")); // NOI18N
        DB_User.setName("DB_User"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        Ins.setName("Ins"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ise_test_engine.ISE_Test_EngineApp.class).getContext().getActionMap(ISE_Test_EngineConfigure.class, this);
        Test.setAction(actionMap.get("Test")); // NOI18N
        Test.setText(resourceMap.getString("Test.text")); // NOI18N
        Test.setName("Test"); // NOI18N

        Save.setAction(actionMap.get("Save")); // NOI18N
        Save.setText(resourceMap.getString("Save.text")); // NOI18N
        Save.setName("Save"); // NOI18N

        DB_Pass.setText(resourceMap.getString("DB_Pass.text")); // NOI18N
        DB_Pass.setName("DB_Pass"); // NOI18N

        Pass.setText(resourceMap.getString("Pass.text")); // NOI18N
        Pass.setName("Pass"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Test)))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Save)
                    .addComponent(Server, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Pass, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DB_Pass, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DB_User, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DB, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Ins, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Port, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Server, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Ins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(DB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DB_User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(DB_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test)
                    .addComponent(Save))
                .addContainerGap())
        );

        Con.setText(resourceMap.getString("Con.text")); // NOI18N
        Con.setName("Con"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(Con)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Con)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
     /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ISE_Test_EngineConfigure().setVisible(true);
            }
        });
    }

    @Action
    public void Test() throws ClassNotFoundException {

        String N2 ="";
        String text_DB = DB.getText();
        String text_DB_Pass = DB_Pass.getText();
        String text_DB_User = DB_User.getText();
        String text_Ins = Ins.getText();
        String text_Port = Port.getText();
        String text_Server = Server.getText();
        String S = text_Server;
        if (!text_Ins.isEmpty()) {
        String N = S.concat("\\");
         N2  = N.concat(text_Ins);
        //System.out.print(N2);
        }else{
          N2 = S;
        }
       
        Connect con = new Connect(N2, text_Port, text_DB, text_DB_User, text_DB_Pass);
        con.getConnection();
        String Conn = con.Test();
        
        // javax.swing.JLabel J = new javax.swing.JLabel("Test");
        //jPanel1.add(J);
        Con.setText(Conn);
        jPanel1.validate();
        
        jPanel1.repaint();
       //Top.paintComponents(J);

       if (con != null) try { con.closeConnection(); } catch(Exception e) {}

        //System.out.print(con.getConnection());
    }
/*public void paint(Graphics g) {
	// Draw rectangle around applet's display area
	g.drawRect(0, 0, getSize().width - 1, getSize().height - 1);


	    Top.paint(g);
	    Top.paintComponents(g);

    }*/

    @Action
    public void Save() throws InvalidKeyException, NoSuchAlgorithmException, InvalidKeySpecException {
        String N2 ="";
        String text_DB = DB.getText();
        String text_DB_Pass = DB_Pass.getText();
        String text_DB_User = DB_User.getText();
        String text_Ins = Ins.getText();
        String text_Port = Port.getText();
        String text_Server = Server.getText();
        String S = text_Server;
        if (!text_Ins.isEmpty()) {
        String N = S.concat("\\");
         N2  = N.concat(text_Ins);
        //System.out.print(N2);
        }else{
          N2 = S;
        }
        String admin = Admin.getText();
        String pass = Pass.getText();
        Config_Text Conf = new Config_Text(text_DB,text_DB_Pass,text_DB_User,N2,text_Port,admin,pass);
        try {
            Conf.write();
        } catch (IOException err){
            
        }

        ISE_Test_EngineApp app =  ISE_Test_EngineApp.getApplication();
              
               app.startup();
               this.setVisible(false);
               //app.exit();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Admin;
    private javax.swing.JLabel Con;
    private javax.swing.JTextField DB;
    private javax.swing.JPasswordField DB_Pass;
    private javax.swing.JTextField DB_User;
    private javax.swing.JTextField Ins;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JTextField Port;
    private javax.swing.JButton Save;
    private javax.swing.JTextField Server;
    private javax.swing.JButton Test;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
   
}
