/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * login.java
 *
 * Created on Aug 6, 2010, 9:59:23 AM
 */

package ise_test_engine;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.*;
import com.microsoft.sqlserver.jdbc.*;
import java.lang.reflect.*;
import org.jdesktop.application.Action;


/**
 *
 * @author TOSHIBA
 */
public class login extends javax.swing.JFrame {
    String Name;
    Config_Text con = new Config_Text();
    /** Creates new form login */
    public login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Login_Mode = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        login_failed = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        Login_Mode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "                    ", "Administrator", "Candidate" }));
        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ise_test_engine.ISE_Test_EngineApp.class).getContext().getActionMap(login.class, this);
        Login_Mode.setAction(actionMap.get("Mode")); // NOI18N
        Login_Mode.setName("Login_Mode"); // NOI18N
        Login_Mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ModeActionPerformed(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ise_test_engine.ISE_Test_EngineApp.class).getContext().getResourceMap(login.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        User.setText(resourceMap.getString("User.text")); // NOI18N
        User.setName("User"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        pass.setText(resourceMap.getString("pass.text")); // NOI18N
        pass.setName("pass"); // NOI18N

        jButton1.setAction(actionMap.get("Login")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        login_failed.setForeground(resourceMap.getColor("login_failed.foreground")); // NOI18N
        login_failed.setText(resourceMap.getString("login_failed.text")); // NOI18N
        login_failed.setName("login_failed"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(jButton1)
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(login_failed, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Login_Mode, javax.swing.GroupLayout.Alignment.LEADING, 0, 259, Short.MAX_VALUE)
                    .addComponent(pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(User, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addGap(89, 89, 89))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Login_Mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(login_failed, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Login_ModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ModeActionPerformed
 javax.swing.JComboBox cb = (javax.swing.JComboBox)evt.getSource();
        Name = (String)cb.getSelectedItem();
         // TODO add your handling code here:
    }//GEN-LAST:event_Login_ModeActionPerformed
private static Method findMain(Class clazz)
throws Exception
{
Method[] methods = clazz.getMethods();
for (int i=0; i<methods.length; i++)
{
if (methods[i].getName().equals("main"))
return methods[i];
}
return null;
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    @Action
    public void Login() throws InvalidKeyException, NoSuchAlgorithmException, InvalidKeySpecException, SQLException, ClassNotFoundException, UnsupportedEncodingException {
        String username = User.getText();
        String Password = pass.getText();
        try{
                con.read();
            }catch (IOException err){


        }
 if (Name.equalsIgnoreCase("Administrator")){
           
            
            if (username.equals(con.admin) && Password.equals(con.pass)){
                ISE_Test_EngineApp app =  ISE_Test_EngineApp.getInstance(ISE_Test_EngineApp.class);

               app.startup();
               this.setVisible(false);
            }else
                login_failed.setText("Lon In Failed");
        jPanel1.validate();

        jPanel1.repaint();

        }//if Name
 else if ( Name.equalsIgnoreCase("Candidate")) {
     
           
     
         Connection con11 = null;

      //Statement stmt = null;
      //ResultSet rs = null;
       SQLServerDataSource ds = new SQLServerDataSource();
       ds.setUser(con.DB_user);
         ds.setPassword(con.DB_Pass);
         ds.setServerName(con.Server);
         ds.setPortNumber(Integer.parseInt(con.Port));
         ds.setDatabaseName(con.DB);
         con11 = ds.getConnection();

     
       //  String SHA_Pass = SHA.SHA(Password);
         String SHA_Pass = Password;
    Statement stmt = con11.createStatement();
    String Sel = "SELECT ID FROM dbo.Candidate Where Uname='" + username + "'" + "AND Password ="+"'" + SHA_Pass+"'";
    ResultSet cursor = stmt.executeQuery(Sel);

    if (!cursor.next()){
            login_failed.setText("Lon In Failed");
        jPanel1.validate();

        jPanel1.repaint();
    }
 else {
        int uid = cursor.getInt("ID");
        //System.out.println(uid);
        String [] str = {String.valueOf(uid)};
        
        try {
           // Tests tset = new Tests(uid);
            Class c = Class.forName("ise_test_engine.Tests");
            
            Method mainMethod = findMain(c);
            mainMethod.invoke(null, new Object[] { str });

         }
         catch (Throwable e) {
            System.err.println(e);
         }
        this.setVisible(false);
        //Tests Test = new Tests(uid);
       /*ava.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tests.main(Integer.parseInt(uid));
            }
        });
*/
        
        }
     if (cursor != null) try { cursor.close(); } catch(Exception e) {}
         if (stmt != null) try { stmt.close(); } catch(Exception e) {}
         if (con11 != null) try { con11.close(); } catch(Exception e) {}
   //  ResultSet rs = stmt.executeQuery("SELECT Lname FROM Customers WHERE Snum = 2001");
        }
 else{
            System.out.print("nothing");
 }          }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Login_Mode;
    private javax.swing.JTextField User;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login_failed;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables

}
