//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Attendance.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EventEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EventEntities object using the connection string found in the 'EventEntities' section of the application configuration file.
        /// </summary>
        public EventEntities() : base("name=EventEntities", "EventEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EventEntities object.
        /// </summary>
        public EventEntities(string connectionString) : base(connectionString, "EventEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EventEntities object.
        /// </summary>
        public EventEntities(EntityConnection connection) : base(connection, "EventEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_EVENT_LOG> TB_EVENT_LOG
        {
            get
            {
                if ((_TB_EVENT_LOG == null))
                {
                    _TB_EVENT_LOG = base.CreateObjectSet<TB_EVENT_LOG>("TB_EVENT_LOG");
                }
                return _TB_EVENT_LOG;
            }
        }
        private ObjectSet<TB_EVENT_LOG> _TB_EVENT_LOG;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_EVENT_LOG EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_EVENT_LOG(TB_EVENT_LOG tB_EVENT_LOG)
        {
            base.AddObject("TB_EVENT_LOG", tB_EVENT_LOG);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BioStarModel", Name="TB_EVENT_LOG")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_EVENT_LOG : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_EVENT_LOG object.
        /// </summary>
        /// <param name="nEventLogIdn">Initial value of the nEventLogIdn property.</param>
        /// <param name="nDateTime">Initial value of the nDateTime property.</param>
        /// <param name="nReaderIdn">Initial value of the nReaderIdn property.</param>
        /// <param name="nEventIdn">Initial value of the nEventIdn property.</param>
        /// <param name="nUserID">Initial value of the nUserID property.</param>
        /// <param name="nIsLog">Initial value of the nIsLog property.</param>
        /// <param name="nTNAEvent">Initial value of the nTNAEvent property.</param>
        /// <param name="nIsUseTA">Initial value of the nIsUseTA property.</param>
        /// <param name="nType">Initial value of the nType property.</param>
        public static TB_EVENT_LOG CreateTB_EVENT_LOG(global::System.Int32 nEventLogIdn, global::System.Int32 nDateTime, global::System.Int32 nReaderIdn, global::System.Int32 nEventIdn, global::System.Int32 nUserID, global::System.Int16 nIsLog, global::System.Int16 nTNAEvent, global::System.Int16 nIsUseTA, global::System.Int16 nType)
        {
            TB_EVENT_LOG tB_EVENT_LOG = new TB_EVENT_LOG();
            tB_EVENT_LOG.nEventLogIdn = nEventLogIdn;
            tB_EVENT_LOG.nDateTime = nDateTime;
            tB_EVENT_LOG.nReaderIdn = nReaderIdn;
            tB_EVENT_LOG.nEventIdn = nEventIdn;
            tB_EVENT_LOG.nUserID = nUserID;
            tB_EVENT_LOG.nIsLog = nIsLog;
            tB_EVENT_LOG.nTNAEvent = nTNAEvent;
            tB_EVENT_LOG.nIsUseTA = nIsUseTA;
            tB_EVENT_LOG.nType = nType;
            return tB_EVENT_LOG;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nEventLogIdn
        {
            get
            {
                return _nEventLogIdn;
            }
            set
            {
                OnnEventLogIdnChanging(value);
                ReportPropertyChanging("nEventLogIdn");
                _nEventLogIdn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nEventLogIdn");
                OnnEventLogIdnChanged();
            }
        }
        private global::System.Int32 _nEventLogIdn;
        partial void OnnEventLogIdnChanging(global::System.Int32 value);
        partial void OnnEventLogIdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nDateTime
        {
            get
            {
                return _nDateTime;
            }
            set
            {
                if (_nDateTime != value)
                {
                    OnnDateTimeChanging(value);
                    ReportPropertyChanging("nDateTime");
                    _nDateTime = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nDateTime");
                    OnnDateTimeChanged();
                }
            }
        }
        private global::System.Int32 _nDateTime;
        partial void OnnDateTimeChanging(global::System.Int32 value);
        partial void OnnDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nReaderIdn
        {
            get
            {
                return _nReaderIdn;
            }
            set
            {
                if (_nReaderIdn != value)
                {
                    OnnReaderIdnChanging(value);
                    ReportPropertyChanging("nReaderIdn");
                    _nReaderIdn = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nReaderIdn");
                    OnnReaderIdnChanged();
                }
            }
        }
        private global::System.Int32 _nReaderIdn;
        partial void OnnReaderIdnChanging(global::System.Int32 value);
        partial void OnnReaderIdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nEventIdn
        {
            get
            {
                return _nEventIdn;
            }
            set
            {
                if (_nEventIdn != value)
                {
                    OnnEventIdnChanging(value);
                    ReportPropertyChanging("nEventIdn");
                    _nEventIdn = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nEventIdn");
                    OnnEventIdnChanged();
                }
            }
        }
        private global::System.Int32 _nEventIdn;
        partial void OnnEventIdnChanging(global::System.Int32 value);
        partial void OnnEventIdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nUserID
        {
            get
            {
                return _nUserID;
            }
            set
            {
                if (_nUserID != value)
                {
                    OnnUserIDChanging(value);
                    ReportPropertyChanging("nUserID");
                    _nUserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nUserID");
                    OnnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _nUserID;
        partial void OnnUserIDChanging(global::System.Int32 value);
        partial void OnnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 nIsLog
        {
            get
            {
                return _nIsLog;
            }
            set
            {
                OnnIsLogChanging(value);
                ReportPropertyChanging("nIsLog");
                _nIsLog = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nIsLog");
                OnnIsLogChanged();
            }
        }
        private global::System.Int16 _nIsLog;
        partial void OnnIsLogChanging(global::System.Int16 value);
        partial void OnnIsLogChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 nTNAEvent
        {
            get
            {
                return _nTNAEvent;
            }
            set
            {
                OnnTNAEventChanging(value);
                ReportPropertyChanging("nTNAEvent");
                _nTNAEvent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nTNAEvent");
                OnnTNAEventChanged();
            }
        }
        private global::System.Int16 _nTNAEvent;
        partial void OnnTNAEventChanging(global::System.Int16 value);
        partial void OnnTNAEventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 nIsUseTA
        {
            get
            {
                return _nIsUseTA;
            }
            set
            {
                OnnIsUseTAChanging(value);
                ReportPropertyChanging("nIsUseTA");
                _nIsUseTA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nIsUseTA");
                OnnIsUseTAChanged();
            }
        }
        private global::System.Int16 _nIsUseTA;
        partial void OnnIsUseTAChanging(global::System.Int16 value);
        partial void OnnIsUseTAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 nType
        {
            get
            {
                return _nType;
            }
            set
            {
                OnnTypeChanging(value);
                ReportPropertyChanging("nType");
                _nType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nType");
                OnnTypeChanged();
            }
        }
        private global::System.Int16 _nType;
        partial void OnnTypeChanging(global::System.Int16 value);
        partial void OnnTypeChanged();

        #endregion
    
    }

    #endregion
    
}
