//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Attendance.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LeaveEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LeaveEntities object using the connection string found in the 'LeaveEntities' section of the application configuration file.
        /// </summary>
        public LeaveEntities() : base("name=LeaveEntities", "LeaveEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LeaveEntities object.
        /// </summary>
        public LeaveEntities(string connectionString) : base(connectionString, "LeaveEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LeaveEntities object.
        /// </summary>
        public LeaveEntities(EntityConnection connection) : base(connection, "LeaveEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Leave> Leaves
        {
            get
            {
                if ((_Leaves == null))
                {
                    _Leaves = base.CreateObjectSet<Leave>("Leaves");
                }
                return _Leaves;
            }
        }
        private ObjectSet<Leave> _Leaves;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Leaves EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLeaves(Leave leave)
        {
            base.AddObject("Leaves", leave);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ATTModel1", Name="Leave")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Leave : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Leave object.
        /// </summary>
        /// <param name="l_ID">Initial value of the L_ID property.</param>
        /// <param name="lT">Initial value of the LT property.</param>
        /// <param name="emp_Id">Initial value of the Emp_Id property.</param>
        /// <param name="dFrom">Initial value of the DFrom property.</param>
        /// <param name="dTo">Initial value of the DTo property.</param>
        public static Leave CreateLeave(global::System.Int32 l_ID, global::System.Int32 lT, global::System.Int32 emp_Id, global::System.DateTime dFrom, global::System.DateTime dTo)
        {
            Leave leave = new Leave();
            leave.L_ID = l_ID;
            leave.LT = lT;
            leave.Emp_Id = emp_Id;
            leave.DFrom = dFrom;
            leave.DTo = dTo;
            return leave;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 L_ID
        {
            get
            {
                return _L_ID;
            }
            set
            {
                if (_L_ID != value)
                {
                    OnL_IDChanging(value);
                    ReportPropertyChanging("L_ID");
                    _L_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("L_ID");
                    OnL_IDChanged();
                }
            }
        }
        private global::System.Int32 _L_ID;
        partial void OnL_IDChanging(global::System.Int32 value);
        partial void OnL_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LT
        {
            get
            {
                return _LT;
            }
            set
            {
                OnLTChanging(value);
                ReportPropertyChanging("LT");
                _LT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LT");
                OnLTChanged();
            }
        }
        private global::System.Int32 _LT;
        partial void OnLTChanging(global::System.Int32 value);
        partial void OnLTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Emp_Id
        {
            get
            {
                return _Emp_Id;
            }
            set
            {
                OnEmp_IdChanging(value);
                ReportPropertyChanging("Emp_Id");
                _Emp_Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Emp_Id");
                OnEmp_IdChanged();
            }
        }
        private global::System.Int32 _Emp_Id;
        partial void OnEmp_IdChanging(global::System.Int32 value);
        partial void OnEmp_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DFrom
        {
            get
            {
                return _DFrom;
            }
            set
            {
                OnDFromChanging(value);
                ReportPropertyChanging("DFrom");
                _DFrom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DFrom");
                OnDFromChanged();
            }
        }
        private global::System.DateTime _DFrom;
        partial void OnDFromChanging(global::System.DateTime value);
        partial void OnDFromChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DTo
        {
            get
            {
                return _DTo;
            }
            set
            {
                OnDToChanging(value);
                ReportPropertyChanging("DTo");
                _DTo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DTo");
                OnDToChanged();
            }
        }
        private global::System.DateTime _DTo;
        partial void OnDToChanging(global::System.DateTime value);
        partial void OnDToChanged();

        #endregion
    
    }

    #endregion
    
}
