//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Attendance.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Leave_Type_Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Leave_Type_Entities object using the connection string found in the 'Leave_Type_Entities' section of the application configuration file.
        /// </summary>
        public Leave_Type_Entities() : base("name=Leave_Type_Entities", "Leave_Type_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Leave_Type_Entities object.
        /// </summary>
        public Leave_Type_Entities(string connectionString) : base(connectionString, "Leave_Type_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Leave_Type_Entities object.
        /// </summary>
        public Leave_Type_Entities(EntityConnection connection) : base(connection, "Leave_Type_Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LeaveType> LeaveTypes
        {
            get
            {
                if ((_LeaveTypes == null))
                {
                    _LeaveTypes = base.CreateObjectSet<LeaveType>("LeaveTypes");
                }
                return _LeaveTypes;
            }
        }
        private ObjectSet<LeaveType> _LeaveTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LeaveTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLeaveTypes(LeaveType leaveType)
        {
            base.AddObject("LeaveTypes", leaveType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ATTModel", Name="LeaveType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LeaveType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LeaveType object.
        /// </summary>
        /// <param name="lT_ID">Initial value of the LT_ID property.</param>
        /// <param name="lT_Name">Initial value of the LT_Name property.</param>
        public static LeaveType CreateLeaveType(global::System.Int32 lT_ID, global::System.String lT_Name)
        {
            LeaveType leaveType = new LeaveType();
            leaveType.LT_ID = lT_ID;
            leaveType.LT_Name = lT_Name;
            return leaveType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LT_ID
        {
            get
            {
                return _LT_ID;
            }
            set
            {
                if (_LT_ID != value)
                {
                    OnLT_IDChanging(value);
                    ReportPropertyChanging("LT_ID");
                    _LT_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LT_ID");
                    OnLT_IDChanged();
                }
            }
        }
        private global::System.Int32 _LT_ID;
        partial void OnLT_IDChanging(global::System.Int32 value);
        partial void OnLT_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LT_Name
        {
            get
            {
                return _LT_Name;
            }
            set
            {
                OnLT_NameChanging(value);
                ReportPropertyChanging("LT_Name");
                _LT_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LT_Name");
                OnLT_NameChanged();
            }
        }
        private global::System.String _LT_Name;
        partial void OnLT_NameChanging(global::System.String value);
        partial void OnLT_NameChanged();

        #endregion
    
    }

    #endregion
    
}
