//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Attendance.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UsersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new UsersEntities object using the connection string found in the 'UsersEntities' section of the application configuration file.
        /// </summary>
        public UsersEntities() : base("name=UsersEntities", "UsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UsersEntities object.
        /// </summary>
        public UsersEntities(string connectionString) : base(connectionString, "UsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UsersEntities object.
        /// </summary>
        public UsersEntities(EntityConnection connection) : base(connection, "UsersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TB_USER> TB_USER
        {
            get
            {
                if ((_TB_USER == null))
                {
                    _TB_USER = base.CreateObjectSet<TB_USER>("TB_USER");
                }
                return _TB_USER;
            }
        }
        private ObjectSet<TB_USER> _TB_USER;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TB_USER EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTB_USER(TB_USER tB_USER)
        {
            base.AddObject("TB_USER", tB_USER);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Users", Name="TB_USER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TB_USER : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TB_USER object.
        /// </summary>
        /// <param name="nUserIdn">Initial value of the nUserIdn property.</param>
        /// <param name="sUserName">Initial value of the sUserName property.</param>
        /// <param name="nDepartmentIdn">Initial value of the nDepartmentIdn property.</param>
        /// <param name="sTelNumber">Initial value of the sTelNumber property.</param>
        /// <param name="sEmail">Initial value of the sEmail property.</param>
        /// <param name="sUserID">Initial value of the sUserID property.</param>
        /// <param name="sPassword">Initial value of the sPassword property.</param>
        /// <param name="nStartDate">Initial value of the nStartDate property.</param>
        /// <param name="nEndDate">Initial value of the nEndDate property.</param>
        /// <param name="nAdminLevel">Initial value of the nAdminLevel property.</param>
        /// <param name="nAuthMode">Initial value of the nAuthMode property.</param>
        /// <param name="nAuthLimitCount">Initial value of the nAuthLimitCount property.</param>
        /// <param name="nTimedAPB">Initial value of the nTimedAPB property.</param>
        /// <param name="bPassword2">Initial value of the bPassword2 property.</param>
        public static TB_USER CreateTB_USER(global::System.Int32 nUserIdn, global::System.String sUserName, global::System.Int32 nDepartmentIdn, global::System.String sTelNumber, global::System.String sEmail, global::System.String sUserID, global::System.String sPassword, global::System.Int32 nStartDate, global::System.Int32 nEndDate, global::System.Int32 nAdminLevel, global::System.Int32 nAuthMode, global::System.Int32 nAuthLimitCount, global::System.Int32 nTimedAPB, global::System.Byte[] bPassword2)
        {
            TB_USER tB_USER = new TB_USER();
            tB_USER.nUserIdn = nUserIdn;
            tB_USER.sUserName = sUserName;
            tB_USER.nDepartmentIdn = nDepartmentIdn;
            tB_USER.sTelNumber = sTelNumber;
            tB_USER.sEmail = sEmail;
            tB_USER.sUserID = sUserID;
            tB_USER.sPassword = sPassword;
            tB_USER.nStartDate = nStartDate;
            tB_USER.nEndDate = nEndDate;
            tB_USER.nAdminLevel = nAdminLevel;
            tB_USER.nAuthMode = nAuthMode;
            tB_USER.nAuthLimitCount = nAuthLimitCount;
            tB_USER.nTimedAPB = nTimedAPB;
            tB_USER.bPassword2 = bPassword2;
            return tB_USER;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nUserIdn
        {
            get
            {
                return _nUserIdn;
            }
            set
            {
                if (_nUserIdn != value)
                {
                    OnnUserIdnChanging(value);
                    ReportPropertyChanging("nUserIdn");
                    _nUserIdn = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("nUserIdn");
                    OnnUserIdnChanged();
                }
            }
        }
        private global::System.Int32 _nUserIdn;
        partial void OnnUserIdnChanging(global::System.Int32 value);
        partial void OnnUserIdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sUserName
        {
            get
            {
                return _sUserName;
            }
            set
            {
                OnsUserNameChanging(value);
                ReportPropertyChanging("sUserName");
                _sUserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sUserName");
                OnsUserNameChanged();
            }
        }
        private global::System.String _sUserName;
        partial void OnsUserNameChanging(global::System.String value);
        partial void OnsUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nDepartmentIdn
        {
            get
            {
                return _nDepartmentIdn;
            }
            set
            {
                OnnDepartmentIdnChanging(value);
                ReportPropertyChanging("nDepartmentIdn");
                _nDepartmentIdn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nDepartmentIdn");
                OnnDepartmentIdnChanged();
            }
        }
        private global::System.Int32 _nDepartmentIdn;
        partial void OnnDepartmentIdnChanging(global::System.Int32 value);
        partial void OnnDepartmentIdnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sTelNumber
        {
            get
            {
                return _sTelNumber;
            }
            set
            {
                OnsTelNumberChanging(value);
                ReportPropertyChanging("sTelNumber");
                _sTelNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sTelNumber");
                OnsTelNumberChanged();
            }
        }
        private global::System.String _sTelNumber;
        partial void OnsTelNumberChanging(global::System.String value);
        partial void OnsTelNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sEmail
        {
            get
            {
                return _sEmail;
            }
            set
            {
                OnsEmailChanging(value);
                ReportPropertyChanging("sEmail");
                _sEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sEmail");
                OnsEmailChanged();
            }
        }
        private global::System.String _sEmail;
        partial void OnsEmailChanging(global::System.String value);
        partial void OnsEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sUserID
        {
            get
            {
                return _sUserID;
            }
            set
            {
                OnsUserIDChanging(value);
                ReportPropertyChanging("sUserID");
                _sUserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sUserID");
                OnsUserIDChanged();
            }
        }
        private global::System.String _sUserID;
        partial void OnsUserIDChanging(global::System.String value);
        partial void OnsUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sPassword
        {
            get
            {
                return _sPassword;
            }
            set
            {
                OnsPasswordChanging(value);
                ReportPropertyChanging("sPassword");
                _sPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sPassword");
                OnsPasswordChanged();
            }
        }
        private global::System.String _sPassword;
        partial void OnsPasswordChanging(global::System.String value);
        partial void OnsPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nStartDate
        {
            get
            {
                return _nStartDate;
            }
            set
            {
                OnnStartDateChanging(value);
                ReportPropertyChanging("nStartDate");
                _nStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nStartDate");
                OnnStartDateChanged();
            }
        }
        private global::System.Int32 _nStartDate;
        partial void OnnStartDateChanging(global::System.Int32 value);
        partial void OnnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nEndDate
        {
            get
            {
                return _nEndDate;
            }
            set
            {
                OnnEndDateChanging(value);
                ReportPropertyChanging("nEndDate");
                _nEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nEndDate");
                OnnEndDateChanged();
            }
        }
        private global::System.Int32 _nEndDate;
        partial void OnnEndDateChanging(global::System.Int32 value);
        partial void OnnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nAdminLevel
        {
            get
            {
                return _nAdminLevel;
            }
            set
            {
                OnnAdminLevelChanging(value);
                ReportPropertyChanging("nAdminLevel");
                _nAdminLevel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nAdminLevel");
                OnnAdminLevelChanged();
            }
        }
        private global::System.Int32 _nAdminLevel;
        partial void OnnAdminLevelChanging(global::System.Int32 value);
        partial void OnnAdminLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nAuthMode
        {
            get
            {
                return _nAuthMode;
            }
            set
            {
                OnnAuthModeChanging(value);
                ReportPropertyChanging("nAuthMode");
                _nAuthMode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nAuthMode");
                OnnAuthModeChanged();
            }
        }
        private global::System.Int32 _nAuthMode;
        partial void OnnAuthModeChanging(global::System.Int32 value);
        partial void OnnAuthModeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nAuthLimitCount
        {
            get
            {
                return _nAuthLimitCount;
            }
            set
            {
                OnnAuthLimitCountChanging(value);
                ReportPropertyChanging("nAuthLimitCount");
                _nAuthLimitCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nAuthLimitCount");
                OnnAuthLimitCountChanged();
            }
        }
        private global::System.Int32 _nAuthLimitCount;
        partial void OnnAuthLimitCountChanging(global::System.Int32 value);
        partial void OnnAuthLimitCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nTimedAPB
        {
            get
            {
                return _nTimedAPB;
            }
            set
            {
                OnnTimedAPBChanging(value);
                ReportPropertyChanging("nTimedAPB");
                _nTimedAPB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nTimedAPB");
                OnnTimedAPBChanged();
            }
        }
        private global::System.Int32 _nTimedAPB;
        partial void OnnTimedAPBChanging(global::System.Int32 value);
        partial void OnnTimedAPBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] bPassword2
        {
            get
            {
                return StructuralObject.GetValidValue(_bPassword2);
            }
            set
            {
                OnbPassword2Changing(value);
                ReportPropertyChanging("bPassword2");
                _bPassword2 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("bPassword2");
                OnbPassword2Changed();
            }
        }
        private global::System.Byte[] _bPassword2;
        partial void OnbPassword2Changing(global::System.Byte[] value);
        partial void OnbPassword2Changed();

        #endregion
    
    }

    #endregion
    
}
